### ISSUE TITLE
idle-countdown Directive Not Updating Countdown Value

### ISSUE THREAD

**Issue by dustymiller** [HackedByChinese/ng-idle#75]
Copied your demo warning dialog $modal code into an existing project.  Modal dialog template is on a page that is handled by an existing controller using ngRoute.  IdleWarn message fires, but the idleCountdown value is not updated due to the following error:

Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.2.25/$rootScope/inprog?p0=%24digest
   at beginPhase (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:22801:9)
   at Scope.prototype.$apply (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:22590:11)
   **at Anonymous function (http://localhost:55287/Scripts/dev/lib/angular-idle.js:310:25)**
   at Scope.prototype.$broadcast (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:22772:15)
   **at countdown (http://localhost:55287/Scripts/dev/lib/angular-idle.js:175:25)**
   at wrappedProgressback (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:21382:15)
   at Anonymous function (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:21350:17)
   at Scope.prototype.$eval (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:22493:9)
   at Scope.prototype.$digest (http://localhost:55287/Scripts/dev/lib/angular-scenario.js:22305:15)
   at Anonymous function (http://localhost:55287/Scripts/d

I commented out the $scope.$apply in the IdleWarn message callback function, and the countdown works as expected.  Same error is also raised in IdleTimeout message handler callback function on line 315.  Do we need to be in a $scope.$apply here?

**Comment by HackedByChinese** [comment]
I think this is an issue between AngularJS 1.2 and 1.3. In 1.3 you need the `$apply` call, but in 1.2 you don't. I need to figure out if a digest is in progress and act accordingly, or figure out how to schedule the action for the next available digest.

**Comment by dustymiller** [comment]
Thanks, Mike.  Our project is on 1.2.28.

**Comment by HackedByChinese** [comment]
Rather than use `$apply`, I switched to `$evalSync` which should guarantee that the changes made in the expression will happen either during the current digest or cause another digest if one isn't happening. Try a copy from the developer branch to see if it resolves your issue and reopen if it doesn't. I did try it against 1.3.x and 1.2.27 and it looks good in both so far.

**Comment by Saabertooth** [comment]
I am on Angular v. 1.3.15 and it seems that while the countdown argument in the 'IdleWarn' event is in fact being updated, changes made to $scope within the event still require being wrapped in $apply

**Comment by astopo** [comment]
+1
